### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by Rodrigo-Barros** [Lt-Mayonesa/browser-mpris2#4]
This is not a bug or anything else, I tested with Firefox, and would like to know why the browser-mpris2 is running when it's no playing sound on "browser", when I let opened a only a new tab, the browser-mpris2 process is killed, when I enter any website even if it is not on the support list the process start running.
Sorry for my grammar.

**Comment by lt-mayonesa** [comment]
Hey, the native app is controlled by the browser see [chrome docs](https://developer.chrome.com/extensions/nativeMessaging) or [firefox docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) for more info. 

To my understanding, the process is started when the browser starts and just "waits" for a page to connect to it.

> when I let opened a only a new tab, the browser-mpris2 process is killed

It looks like Firefox kills the process when it knows it doesn't need it. But again, it's controlled by the browser, not by the extension.

(if you have any more questions feel free to re-open the issue)

**Comment by Rodrigo-Barros** [comment]
Hey @Lt-Mayonesa,  after install your extension I understand the why works this way, even I am not on supported sites, I still able to play and pause and it is a nice behaviour for your extension, that's all, great addon, congratulations.
